deployment:
  tasks:
    - /usr/bin/git reset --hard HEAD
    - /usr/bin/git clean -fdx
    - /home/brandbanao/nodevenv/nodeapp/18.20.8/bin/npm ci
    - /home/brandbanao/nodevenv/nodeapp/18.20.8/bin/npm run build
    - /bin/rsync -a --delete ./dist/ /home/brandbanao/public_html/site-v2/
