# .cpanel.yml  — Vite → public_html (user: brandbanao)
deployment:
  tasks:
    # keep the working tree clean for cPanel
    - /usr/bin/git reset --hard HEAD
    - /usr/bin/git clean -fdx

    # build (uses the Node/npm available on your account)
    - npm ci
    - npm run build

    # deploy built files
    - /bin/rsync -a --delete ./dist/ /home/brandbanao/public_html/

    # optional: remove build artifacts so next deploy starts clean
    - /bin/rm -rf ./dist
